<?php
//$Id$

/*
 * Implementation of hook_form_alter().
 */
function svrgc_form_alter(&$form, &$form_state, $form_id) {
//  kpr($form);
  //allow arguments to preselect the contact form category
  if (($form_id == 'contact_mail_page') && is_numeric(arg(1))) {
    $form['cid']['#default_value'] = arg(1);
  }
  //stop the 'caliber' user from changing picture and contact form settings
  global $user;
  if (($form_id == 'user_profile_form') && ($user->uid == '4')) {
    unset ($form['picture']);
    unset ($form['contact']);
  }
  //stop the 'caliber' user from editing the profile
  if (($form_id == 'profile_node_form') && ($user->uid == '4')) {
    unset ($form['buttons']);
  }
  if ($form_id == 'user_register') {
    $form['name']['#description'] = t('Use the Member\'s name in the format: <strong>"Firstname Lastname"</strong> (no quotes). Capitalize both names and include the space in between.');
  }
}

/*
 * Implementation of hook_form_FORM_ID_alter().
 */
function svrgc_form_bullseye_league_match_node_form_alter(&$form, &$form_state) {

  $yesterday = date('m.d.Y', strtotime('-1 day'));
  $form['title']['#default_value'] = $yesterday;

  $form['#redirect'] = 'node/add/bullseye-league-match';
}

/*
 * Implementation of hook_form_FORM_ID_alter().
 */
function svrgc_form_bullseye_league_handicap_match_node_form_alter(&$form, &$form_state) {

  $yesterday = date('m.d.Y', strtotime('-1 day'));
  $form['title']['#default_value'] = $yesterday;

  $form['#redirect'] = 'node/add/bullseye-league-handicap-match';
}

/*
 * Implementation of hook_imagecache_default_presets().
 */
function svrgc_imagecache_default_presets() {
$presets = array();
$presets['polaroid'] = array (
  'presetname' => 'polaroid',
  'actions' => 
  array (
    0 => 
    array (
      'weight' => '-10',
      'module' => 'imagecache',
      'action' => 'imagecache_scale_and_crop',
      'data' => 
      array (
        'width' => '300',
        'height' => '410',
      ),
    ),
    1 => 
    array (
      'weight' => '-9',
      'module' => 'imagecache_canvasactions',
      'action' => 'canvasactions_definecanvas',
      'data' => 
      array (
        'RGB' => 
        array (
          'HEX' => 'feffc8',
        ),
        'under' => 1,
        'exact' => 
        array (
          'width' => '364',
          'height' => '449',
          'xpos' => '32',
          'ypos' => '14',
        ),
        'relative' => 
        array (
          'leftdiff' => '',
          'rightdiff' => '',
          'topdiff' => '',
          'bottomdiff' => '',
        ),
      ),
    ),
    2 => 
    array (
      'weight' => '-8',
      'module' => 'imagecache_canvasactions',
      'action' => 'canvasactions_file2canvas',
      'data' => 
      array (
        'xpos' => 0,
        'ypos' => 0,
        'alpha' => '100',
        'path' => 'sites/all/modules/imagecache_actions/docs/polaroid-template-transparent.png',
      ),
    ),
  ),
);

$presets['thumbnail'] = array (
  'presetname' => 'thumbnail',
  'actions' => 
  array (
    0 => 
    array (
      'weight' => '0',
      'module' => 'imagecache',
      'action' => 'imagecache_scale',
      'data' => 
      array (
        'width' => '100',
        'height' => '',
        'upscale' => 0,
      ),
    ),
  ),
);
  return $presets;
}

/**
 * Implementation of hook_views_api().
 */
function svrgc_views_api() {
  return array(
    'api' => 2.0,
  );
}
